config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  

  resources :facilities do
    collection do
      get :search
    end
  end

  #resources :facilities

  resources  :facilities do
    resources :appointments
  end
  #get '/search' => 'facilities#search', :as => 'search_page'
  get '/demo' => 'facilities#demo', :as => 'demo_page'
 # root 'facilities#search'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :facility
end

app/models/facility.rb
class Facility < ApplicationRecord
    has_many :appointments, dependent: :destroy
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    #settings do 
    #    mappings dynamic: false do
    #        indexes :title, type: :text
    #        indexes :location, type: :text
    #        indexes :capacity, type: :integer
    #        indexes :price, type: :integer
    #        indexes :environment, type: :text
    #        indexes :description, type: :text
    #    end
    #end

    def self.search_published(query)
        self.search({
          query: {
            bool: {
              must: [
              {
                multi_match: {
                  query: query,
                  fields: [:title, :location, :environment]
                }
              }
              ]
            }
          }
        })
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html.haml { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:title, :location, :check_in, :check_out, :party_size)
    end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]

  # GET /facilities
  # GET /facilities.json

  def index
    @facilities = Facility.all
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
    @facility = Facility.find(params[:id])
  end
  
  def demo
  
  end

  def search
    query = params[:search_facilities].presence && params[:search_facilities][:query]

    if query
      @facilities = Facility.search_published(query)
    end

     
  
  end

  # GET /facilities/new
  def new
    @facility = Facility.new
  end

  # GET /facilities/1/edit
  def edit
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(facility_params)

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility, notice: 'Facility was successfully created.' }
        format.json { render :show, status: :created, location: @facility }
      else
        format.html { render :new }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url, notice: 'Facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:title, :location, :capacity, :environment, :price, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :check_in %>
    <%= form.date_select :check_in %>
  </div>

  <div class="field">
    <%= form.label :check_out %>
    <%= form.date_select :check_out %>
  </div>

  <div class="field">
    <%= form.label :party_size %>
    <%= form.number_field :party_size %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Check in</th>
      <th>Check out</th>
      <th>Party size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.title %></td>
        <td><%= appointment.location %></td>
        <td><%= appointment.check_in %></td>
        <td><%= appointment.check_out %></td>
        <td><%= appointment.party_size %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.haml
%br
%br

.appointment-form
  %h1 Book a facility
  = render 'form', appointment: @appointment
  = link_to 'Back', appointments_path

- form_for facilities_path, :method => 'get' do
  %p
    = text_field_tag :search, params[:search]
    = submit_tag "Search", :name => nil

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @appointment.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @appointment.location %>
</p>

<p>
  <strong>Check in:</strong>
  <%= @appointment.check_in %>
</p>

<p>
  <strong>Check out:</strong>
  <%= @appointment.check_out %>
</p>

<p>
  <strong>Party size:</strong>
  <%= @appointment.party_size %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/facilities/_form.html.erb
<%= form_with(model: facility, local: true) do |form| %>
  <% if facility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(facility.errors.count, "error") %> prohibited this facility from being saved:</h2>

      <ul>
      <% facility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div class="field">
    <%= form.label :environment %>
    <%= form.text_field :environment %>
  </div>

  

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/facilities/demo.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Righteous", :rel => "stylesheet"}/

%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{href: "#"} Domespace
  %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", type: "button"}
    %span.navbar-toggler-icon
  #navbarNav.collapse.navbar-collapse
    %ul.navbar-nav.pull-right
      %li.nav-item.active
        %a.nav-link{href: "#"}
          Home
          %span.sr-only (current)
      %li.nav-item
        %a.nav-link{href: "#"} Facilities
      %li.nav-item
        %a.nav-link{href: "#"} Become a Host
      %li.nav-item
        %a.nav-link.disabled{href: "#"} Sign up

%div
  %h1
    SUNSET RECREATION CENTER - GYMNASIUM
    %small San Francisco, CA
  %div
    %div
      %img{:src => "/app/assets/images/bball.jpg"}/
    %div
      %h3 Facility Description
      %p
        Sunset Recreation Center - Gymnasium is the ideal facility for basketball activities.
        The facility contains 6 basketball hoops to play games or run drills with. This facility also contains bleachers and
        a scoreboard if competitive play is what you are looking for. This facility is located in the Sunset District of San Francisco.
        Street parking is available around the venue.
      %h3 Facility Details
      %ul
        %li
          %strong Address:
          2201 Lawton St, San Francisco, CA 94122
        %li
          %strong Capacity:
          600
        %li
          %strong Equipment:
          Scoreboard; basketball hoops - 6; bleachers
        %li
          %strong Restrooms:
          Yes
  %h3 Photos
  %div
    %h2{:style => "text-align:center"} Slideshow Gallery
    %div
      %div
        %div 1 / 6
        %img{:style => "width:100%"}/
      %div
        %div 2 / 6
        %img{:style => "width:100%"}/
      %div
        %div 3 / 6
        %img{:style => "width:100%"}/
      %div
        %div 4 / 6
        %img{:style => "width:100%"}/
      %div
        %div 5 / 6
        %img{:style => "width:100%"}/
      %div
        %div 6 / 6
        %img{:style => "width:100%"}/
      %a ❮
      %a ❯
      %div
        %p
      %div
        %div
          %img{:alt => "Picture #1", :style => "width:100%"}/
        %div
          %img{:alt => "Picture #2", :style => "width:100%"}/
        %div
          %img{:alt => "Picture #3", :style => "width:100%"}/
        %div
          %img{:alt => "Picture #4", :style => "width:100%"}/
        %div
          %img{:alt => "Picture #5", :style => "width:100%"}/
        %div
          %img{:alt => "Picture #6", :style => "width:100%"}/
  %div

app/views/facilities/edit.html.erb
<h1>Editing Facility</h1>

<%= render 'form', facility: @facility %>

<%= link_to 'Show', @facility %> |
<%= link_to 'Back', facilities_path %>

app/views/facilities/index.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Righteous", :rel => "stylesheet"}/

%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{href: "#"} Domespace
  %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", type: "button"}
    %span.navbar-toggler-icon
  #navbarNav.collapse.navbar-collapse
    %ul.navbar-nav.pull-right
      %li.nav-item.active
        %a.nav-link{href: "#"}
          Home
          %span.sr-only (current)
      %li.nav-item
        %a.nav-link{href: "#"} Facilities
      %li.nav-item
        = link_to 'Become a Host', new_facility_path
      %li.nav-item
        %a.nav-link.disabled{href: "#"} Sign up


%p#notice= notice
%h1.facil.fh 100+ facilities

%br


 
- @facilities.each do |facility|
  %div.dome
    %div.poster
    
    %p.facil_name= facility.title
    //%p= facility.location  
    .stats
      %p.facil_margin Capacity: 
      %p.facil= facility.capacity 
      %p.facil_margin Price per night $
      %p.facil= facility.price
    .facility_type  
      %p.facil_margin Facility Type:  
      %p.facil_margin= facility.environment
    %p= facility.reviews
    %p= facility.comments
    //%p= facility.description
    //%p= link_to 'Show', facility
    //%p= link_to 'Edit', edit_facility_path(facility)
    //%p= link_to 'Destroy', facility, method: :delete, data: { confirm: 'Are you sure?' }
%br/

app/views/facilities/new.html.erb
<h1>New Facility</h1>

<%= render 'form', facility: @facility %>

<%= link_to 'Back', facilities_path %>

app/views/facilities/search.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Righteous", :rel => "stylesheet"}/
%h1 Elastic search for Facilities
= form_for :search_facilities, url: search_facilities_path, method: :get do |form|
  = form.text_field :query, value: params[:search_facilities].presence && params[:search_facilities][:query]
  = form.submit 'Search'
- unless @facilities.nil?
  - if @facilities.empty?
    %h2 No facilities found matching your query.
  - else
    %h2 Search results
    - @facilities.each do |facility|
      %div.dome
        %div.poster
        
        %p.facil_name= facility.title
        //%p= facility.location  
        .stats
          %p.facil_margin Capacity: 
          %p.facil= facility.capacity 
          %p.facil_margin Price per night $
          %p.facil= facility.price
        .facility_type  
          %p.facil_margin Facility Type:  
          %p.facil_margin= facility.environment
        %p= facility.reviews
        %p= facility.comments
        //%p= facility.description
        //%p= link_to 'Show', facility
        //%p= link_to 'Edit', edit_facility_path(facility)
        //%p= link_to 'Destroy', facility, method: :delete, data: { confirm: 'Are you sure?' }
    %br/

app/views/facilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @facility.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @facility.location %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @facility.capacity %>
</p>

<p>
  <strong>Environment:</strong>
  <%= @facility.environment %>
</p>

<p>
  <strong>Reviews:</strong>
  <%= @facility.reviews %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @facility.comments %>
</p>

<p>
  <strong>Description:</strong>
  <%= @facility.description %>
</p>

<%= link_to 'Edit', edit_facility_path(@facility) %> |
<%= link_to 'Back', facilities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Domespace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>